### ISSUE TITLE
Fetch metadata in parallel for a given list of S3 paths

### ISSUE THREAD

**Issue by gsantia** [d3b-center/d3b-utils-python#16]
We want the ingest library to automatically get S3 data during the ingestion process ([issue here](https://github.com/kids-first/kf-lib-data-ingest/issues/628)). Part of this process is fetching the metadata for all S3 paths in a given list, which might be useful in other contexts. It'd be best to abstract it out as a utility function.

**Comment by fiendish** [comment]
I think we have two options for doing this...
The first option I see is a parallel get_object() request for every path. Simple and straightforward but many API requests (tens/hundreds of thousands?).
The second option is:
1. split the list of files into a sublist for each represented bucket (first component of each key)
2. find one (or more) common prefix for each sublist using something like os.path.commonpath
2.5. if the common prefix is just the bucket name, then multiple prefixes exist and we may want to find them?
3. run a list_objects_v2() paginator against each sublist with its prefix. (these should be run in parallel)
4. reduce the pagination results to just the original set of paths

**Comment by fiendish** [comment]
This only allows for one common prefix per bucket
    
```Python
import os
import re
from concurrent.futures import ThreadPoolExecutor


def fetch_obj_list_info(pathlist, profile="saml", all_versions=False):
    bucket_paths = {}
    for path in pathlist:
        bucket, key = re.sub(r"^s3://", "", path, count=1).split("/", 1)
        bucket_paths.setdefault(bucket, set()).add(key)

    def scrape(bucket, prefix):
        return fetch_bucket_obj_info(
            bucket, search_prefixes=[prefix], profile=profile, all_versions=all_versions
        )

    if all_versions:
        found = {"Versions": [], "DeleteMarkers": []}
    else:
        found = []

    with ThreadPoolExecutor() as tpex:
        futures = {
            tpex.submit(scrape, bucket, os.path.commonpath(keys)): bucket
            for bucket, keys in bucket_paths.items()
        }
        for f in as_completed(futures):
            objects = f.result()
            if all_versions:
                found["Versions"].extend(
                    o
                    for o in objects["Versions"]
                    if o["Key"] in bucket_paths[futures[f]]
                )
                found["DeleteMarkers"].extend(
                    o
                    for o in objects["DeleteMarkers"]
                    if o["Key"] in bucket_paths[futures[f]]
                )
            else:
                found.extend(o for o in objects if o["Key"] in bucket_paths[futures[f]])

    return found
```
