### ISSUE TITLE
Consider adding an option to sort by key in _s3meta_to_file() for use case of fetch_aws_bucket_obj_info()

### ISSUE THREAD

**Issue by r3m0chop** [d3b-center/d3b-utils-python#25]
**Is your feature request related to a problem? Please describe.**
Noting that s3 scrapes currently generate columns for which the ordering is not fixed across consecutive calls to `d3b_utils.aws_bucket_contents.fetch_aws_bucket_obj_info()`.  This can require subsequent downstream steps to re-order the s3 scrape into a consistent format, as is particularly useful when `diff`ing across multiple scrapes (e.g., to ensure that particular files have been deleted, or even restored).

**Describe the solution you'd like**
It would be great if... we could introduce an option to `_s3meta_to_file()` that would allow a consistent ordering of the output columns, whether through a supplied list of desired column ordering, or merely by a built-in alphanumeric sort.

**Describe alternatives you've considered**
A rudimentary case-sensitive alphanumeric sort might be implemented by merely wrapping `sorted()` around the assignment the following:
https://github.com/d3b-center/d3b-utils-python/blob/513850413f10b5b72907da71361b81c54c0d843a/d3b_utils/s3_contents.py#L24

such as:
```
        keys = sorted(set(chain(*(d.keys() for d in content))))
```

**Additional context**
Using the following code:
```
#!/usr/bin/python3

from d3b_utils.aws_bucket_contents import fetch_aws_bucket_obj_info as abc

contents= abc (
    bucket_name="kf-strides-study-us-east-1-prd-sd-r0eprsgs" ,
    search_prefixes=["source/"],
    drop_folders=True,
    output_filename="s3_scrape_marazita.csv",
    profile=None,
)
```
 four different calls to the same above code resulted in the following four different headers:
```
$ head -1 *.csv
==> s3_scrape_marazita_2022oct24_2104UTC.csv <==
Key,ETag,StorageClass,Bucket,LastModified,Size

==> s3_scrape_marazita_2022oct25_1509UTC.csv <==
Bucket,Size,Key,ETag,StorageClass,LastModified

==> s3_scrape_marazita_2022oct25_1518UTC.csv <==
ETag,Size,LastModified,Key,StorageClass,Bucket

==> s3_scrape_marazita_2022oct25_1519UTC.csv <==
StorageClass,Key,ETag,Size,Bucket,LastModified

==> s3_scrape_marazita_2022oct25_1730UTC.csv <==
StorageClass,Size,ETag,LastModified,Bucket,Key
```

**Comment by fiendish** [comment]
Given that your goal is consistency and not any particular ordering, the minimal alternative of sorting the keys makes sense to me.
